travis:
  secure:
    BINSTAR_TOKEN: XJoxuPcF5XZS0QK/XFV+9CyITgFommE8Ar6UuHnyzcd7CPgtKXY1OZisHNq6UHGfLFkbY1R2TBNs2URThamR7jjPGYDrGTY7e31bZsVX6ywnvUSbSV4SXwwlQBvhjY4zXjtEXgOFqlz825v6L2PUKZmRm2xRkRcNcociHhMlHI7z3fUfA2YPAwCJBDJ1lfVsTX1jQTAh6fVFdRNDKH34ZdUyx38DANbFC3GMj87lp8Yg4YtQfJLQdzHFQFg9F668gVf9BmAS4LJ2wPU89X7UplOAJKExMQ3HjbXl/QbAr6ZpwGd7ifoOwBc23l1y0mk+o0H8I/evbIKVPIE1hPlq3DUUAMm/k9SI49A4tEYkb7DfYO27ltSNmVx2U9S0wtVqqA7BvC67+gFXHulyLVHvCNOeOpdOVH87HJ/razH9YuNN525Bd5cuJrbrzyIx9K1AiYCISFx2z+8iZykhrtbCmInGmC/N2eKqRr7hGyJFANFAGNHL8AmSJMI24DII6CrzWLRueQ6l06Fw5Rg2TQPjCRFQvKPrjdn5DV/l9Gi0TR9MElluIgUAyvzxuuIA9B/baQnx8dfA4F83ONH2pSMxhRtIWi0pPIRzOemz2He+q8vGPbW7+aRA2tNTW8umzIvPi9ugyZoe6M1sL2hIrmXQYvbvOHJUv3s+JRnoTpxWkX8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
